dokuwiki_translator_homepage:
    pattern:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_plugin_add:
    pattern:  /plugin/add
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:add}

dokuwiki_translate:
    pattern:  /translate
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translateCore}

dokuwiki_translate_plugin:
    pattern:  /translate/plugin/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translatePlugin}
