dokuwiki_translator_homepage:
    pattern:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_plugin_add:
    pattern:  /plugins/add
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:add}

dokuwiki_translator_plugin_add_description:
    pattern:  /plugins/add/description
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:description}

dokuwiki_translator_plugin_show:
    pattern:  /plugin/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:show }