dokuwiki_translator_homepage:
    pattern:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_plugin_add:
    pattern:  /plugin/add
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:add}
