dokuwiki_translator_homepage:
    pattern:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_plugins:
    pattern:  /plugins
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:index}

dokuwiki_translator_plugin_add:
    pattern:  /plugin/add
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:add}

dokuwiki_translator_plugin_add_description:
    pattern:  /plugin/add/description
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:description}