dokuwiki_translator_homepage:
    pattern:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_show_plugin:
    pattern:  /plugin/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Default:show}

dokuwiki_translator_plugin_add:
    pattern:  /plugin
    defaults: { _controller: dokuwikiTranslatorBundle:Plugin:index}

dokuwiki_translator_plugin_activate:
        pattern:  /plugin/{name}/activate/{key}
        defaults: { _controller: dokuwikiTranslatorBundle:Plugin:activate}

dokuwiki_translate:
    pattern:  /translate
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translateCore}

dokuwiki_translate_plugin:
    pattern:  /translate/plugin/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translatePlugin}

dokuwiki_translator_show:
    pattern:  /dokuwiki
    defaults: { _controller: dokuwikiTranslatorBundle:Default:show}
