parameters:
    repository.class: org\dokuwiki\translatorBundle\Services\Repository\Repository
    repository_manager.class: org\dokuwiki\translatorBundle\Services\Repository\RepositoryManager
    repository_stats.class: org\dokuwiki\translatorBundle\Services\Repository\RepositoryStats
    doku_wiki_repository_api.class: org\dokuwiki\translatorBundle\Services\DokuWikiRepositoryAPI\DokuWikiRepositoryAPI
    plugin_name_validator.class: org\dokuwiki\translatorBundle\Validator\PluginNameValidator
    language_manager.class: org\dokuwiki\translatorBundle\Services\Language\LanguageManager

services:
    repository_manager:
        class: "%repository_manager.class%"
        arguments: ["%data%", @doctrine.orm.entity_manager, "%reprositoryUpdateAge%", "%maxRepositoriesToUpdatePerRun%", @repository_stats , @git_service, @mail_service, @git_hub_service, @logger, "%maxErrorCount%"]

    repository_stats:
        class: "%repository_stats.class%"
        arguments: [ @doctrine.orm.entity_manager]

    doku_wiki_repository_api:
        class: "%doku_wiki_repository_api.class%"
        arguments: ["%data%", @doctrine.orm.entity_manager]

    plugin_name_validator:
        class: "%plugin_name_validator.class%"
        tags:
            - { name: validator.constraint_validator, alias: dwplugin }
        calls:
            - [setApi, [@doku_wiki_repository_api]]

    language_manager:
        class: "%language_manager.class%"

    listener.before_controller:
        class: org\dokuwiki\translatorBundle\EventListener\BeforeControllerListener
        scope: "request"
        tags:
            - { name: kernel.event_listener, event: "kernel.controller", method: "onKernelController" }

    git_service:
        class: org\dokuwiki\translatorBundle\Services\Git\GitService
        arguments: ["%git_bin%", "%command_timeout%"]

    mail_service:
        class: org\dokuwiki\translatorBundle\Services\Mail\MailService
        arguments: [@mailer, @twig, "%mailer_from%", @logger]

    git_hub_service:
        class: org\dokuwiki\translatorBundle\Services\GitHub\GitHubService
        arguments: ["%git_hub_token%", "%data%", "%git_hub_url%"]
