parameters:
    git_bin: C:\Program Files (x86)\Git\bin\git.exe # path to the git executable
    data: D:\Temp\test 1                            # path to the working directory

    repository.class: org\dokuwiki\translatorBundle\Services\Repository
    repository_manager.class: org\dokuwiki\translatorBundle\Services\RepositoryManager

services:
    repository:
        class: "%repository.class%"
    repository_manager:
        class: "%repository_manager.class%"
        arguments: ["%data%"]
