parameters:
    git_bin: C:\Program Files (x86)\Git\bin\git.exe # path to the git executable
    data: D:\Temp\test 1                            # path to the working directory

    repository.class: org\dokuwiki\translatorBundle\Services\Repository\Repository
    repository_manager.class: org\dokuwiki\translatorBundle\Services\Repository\RepositoryManager
    doku_wiki_repository_api.class: org\dokuwiki\translatorBundle\Services\DokuWikiRepositoryAPI\DokuWikiRepositoryAPI
    plugin_name_validator.class: org\dokuwiki\translatorBundle\Validator\PluginNameValidator

services:
    repository:
        class: "%repository.class%"
    repository_manager:
        class: "%repository_manager.class%"
        arguments: ["%data%", @doctrine.orm.entity_manager ]
    doku_wiki_repository_api:
        class: "%doku_wiki_repository_api.class%"
        arguments: ["%data%"]

    plugin_name_validator:
        class: "%plugin_name_validator.class%"
        tags:
            - { name: validator.constraint_validator, alias: dwplugin }
        calls:
            - [setApi, [@doku_wiki_repository_api]]
