
org\dokuwiki\translatorBundle\Entity\RepositoryEntity:
    properties:
        url:
            - NotBlank: ~
            - Url: { protocols: [http, https, git, ssh] }
        branch:
            - NotBlank: ~
            - Regex: "/^\S+$/"
        email:
            - NotBlank: ~
            - Email: ~
        name:
            - NotBlank: ~
            - Regex: "/^[a-z0-9]+$/"
            - org\dokuwiki\translatorBundle\Validator\PluginName:
                groups: [plugin]
            - org\dokuwiki\translatorBundle\Validator\TemplateName:
                groups: [template]
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: name, message: "There is already a registered plug-in with this name."}

