
org\dokuwiki\translatorBundle\Entity\RepositoryEntity:
    properties:
        url:
            - NotBlank: ~
            - Url: { protocols: [http, https, git, ssh] }
        branch:
            - NotBlank: ~
            - Regex: "/^\S+$/"
        email:
            - NotBlank: ~
            - Email: ~
        name:
            - NotBlank: ~
            - Regex: "/^\S+$/"
            - org\dokuwiki\translatorBundle\Validator\PluginName: ~

